mysql_db:
    build: dockerfile/mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: root
        MYSQL_PASSWORD: root
php7:
    build: dockerfile/php
    ports: 
        - "9000:9000"
    links: 
        - mysql_db
    volumes:
        - ./icare-employee-management/:/var/www/b2b/employee-management
nginx:
    build: dockerfile/nginx
    ports:
        - "80:80"
    links:
        - php7
    volumes_from: 
        - php7
    volumes: 
        - ./logs/nginx/:/var/log/nginx
